### ISSUE TITLE
license clarity

### ISSUE THREAD

**Issue by microprediction** [mdengler/cla#4]
Hi there. I flagged this as potentially of interest to M6-Competition entrants, but wonder if the license permits. It is unclear to me and perhaps participants whether entering contests constitutes a "commercial activity".

**Comment by mdengler** [comment]
Hi -- thanks for the issue.  We'd have to contact the license holders -- David H. Bailey and Marcos López de Prado -- to confirm permission is granted.  To the extent any permission actually rests with me, permission is granted.
