### ISSUE TITLE
data.csv not found

### ISSUE THREAD

**Issue by i001962** [mdengler/cla#5]
Looks like the domain where the example data is retrieved from is no longer accessible.
http://www.quantresearch.info/CLA_Data.csv.txt

If you provide info on the expected format I'll create some test data and a PR.

**Comment by i001962** [comment]
found it here. Looks like a typo in the readme.md .info should be .org
https://quantresearch.org/CLA_Data.csv.txt

**Comment by mdengler** [comment]
Thanks -- the `README.md` quotes the paper ^[https://deliverypdf.ssrn.com/delivery.php?ID=611103021078107117112006084113065112034072042037055057122116108022104001025122086096028012000000098030047023004072094113107103111025000087019005001009068029117091055086011118029074007126002122090012103074116005001098086099102023125020107007118127097&EXT=pdf&INDEX=TRUE] which mentions `quantresearch.info`, so thanks for the update! 
 I have updated the `README.md`.
